### ISSUE TITLE
SSH Cred for the images

### ISSUE THREAD

**Issue by prott8gf** [abh1nav/docker-cassandra#3]
Hi, 

I would like to access the containers via ssh to run some test, could you provide the login credentials for both images?

For example usage of "nodetool" via ssh 

Thank you

Best Regards 

PJ

**Comment by abh1nav** [comment]
Hi PJ,

This image is based on the [Phusion baseimage](https://github.com/phusion/baseimage-docker). To be able to login via SSH, you'll have to fork the repo and make some modifications. All the steps are laid out in detail [here](https://github.com/phusion/baseimage-docker#login_ssh). Let me know if that works for you.

Cheers!
