### ISSUE TITLE
Overall question

### ISSUE THREAD

**Issue by jquacinella** [abh1nav/docker-cassandra#5]
First things first, this is a great repo. However, I am curious about your description of the project, stating that its used for 'quick dev deployments'. Is there any particular reason why you say that? Should other features of cassandra be enabled / configured that this container does not do?

Thanks for any insight!

**Comment by abh1nav** [comment]
Hi @jquacinella - I created this project almost 2 years ago - back then we were doing a lot of work with Cassandra and there were no easy ways to stand up a local C\* cluster other than [CCM](http://www.datastax.com/dev/blog/ccm-a-development-tool-for-creating-local-cassandra-clusters) (which, at the time, I felt was opaque and hard to understand). Docker gave me an easy way to run clusters for testing and destroy them after I was done leaving no trace on my dev box. Hope that helps.
